config/routes.rb
Audible::Application.routes.draw do
  resources :games

  resources :team_has_os

  resources :team_has_ds

  resources :o_plays

  resources :d_plays

  resources :teams

  root 'home#index'

end

app/models/d_play.rb
class DPlay < ActiveRecord::Base

	has_many :teamHasDs
	
	def dplayname
		"#{name.titleize}"
	end
end

app/controllers/d_plays_controller.rb
class DPlaysController < ApplicationController
  before_action :set_d_play, only: [:show, :edit, :update, :destroy]

  # GET /d_plays
  # GET /d_plays.json
  def index
    @d_plays = DPlay.all
    @d_play = DPlay.new
  end

  # GET /d_plays/1
  # GET /d_plays/1.json
  def show
  end

  # GET /d_plays/new
  def new
    @d_play = DPlay.new
  end

  # GET /d_plays/1/edit
  def edit
  end

  # POST /d_plays
  # POST /d_plays.json
  def create
    @d_play = DPlay.new(d_play_params)

    respond_to do |format|
      if @d_play.save
        format.html { redirect_to @d_play, notice: 'D play was successfully created.' }
        format.json { render action: 'show', status: :created, location: @d_play }
      else
        format.html { render action: 'new' }
        format.json { render json: @d_play.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /d_plays/1
  # PATCH/PUT /d_plays/1.json
  def update
    respond_to do |format|
      if @d_play.update(d_play_params)
        format.html { redirect_to @d_play, notice: 'D play was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @d_play.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /d_plays/1
  # DELETE /d_plays/1.json
  def destroy
    @d_play.destroy
    respond_to do |format|
      format.html { redirect_to d_plays_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_d_play
      @d_play = DPlay.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def d_play_params
      params.require(:d_play).permit(:name, :picture, :formation, :play_type)
    end
end

app/helpers/d_plays_helper.rb
module DPlaysHelper
end

app/views/d_plays/_form.html.erb
<%= form_for(@d_play) do |f| %>
<div id="d-form">
<h1>Add Defensive Play</h1>
	<div class="field">
    	<%= f.label :name %><br>
    	<%= f.text_field :name %>
    </div>
  	<div class="field">
    	<%= f.label :picture %><br>
    	<%= f.text_field :picture %>
  	</div>
  	<div class="field">
    	<%= f.label :formation %><br>
    	<%= f.text_field :formation %>
  	</div>
  	<div class="field">
    	<%= f.label :play_type %><br>
    	<%= f.text_field :play_type %>
  	</div>
  	<div class="actions">
    	<%= f.submit %>
  	</div>
</div>
<% end %>

app/views/d_plays/edit.html.erb
<h1>Editing d_play</h1>

<%= render 'form' %>

<%= link_to 'Show', @d_play %> |
<%= link_to 'Back', d_plays_path %>

app/views/d_plays/index.html.erb
<div id="d-backdrop">
	<div id="d-list">
		<h1>Defensive Plays</h1>
			<% @d_plays.each do |d_play| %>
			<p class="d-playiterate">
				<%= d_play.formation %>
    			<%= d_play.name %>
    			<%= d_play.picture %>	
    			<%= d_play.play_type %>
    			<span>
    				<%= link_to 'Destroy', d_play, method: :delete, data: { confirm: 'Are you sure?' } %>
    			</span>
    		</p>
    		<% end %>
	</div>
	<%= render 'form' %>
</div>

app/views/d_plays/new.html.erb
<h1>New d_play</h1>

<%= render 'form' %>

<%= link_to 'Back', d_plays_path %>

app/views/d_plays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @d_play.name %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @d_play.picture %>
</p>

<p>
  <strong>Formation:</strong>
  <%= @d_play.formation %>
</p>

<p>
  <strong>Play type:</strong>
  <%= @d_play.play_type %>
</p>

<%= link_to 'Edit', edit_d_play_path(@d_play) %> |
<%= link_to 'Back', d_plays_path %>