config/routes.rb
Audible::Application.routes.draw do
  resources :games

  resources :team_has_os

  resources :team_has_ds

  resources :o_plays

  resources :d_plays

  resources :teams

  root 'home#index'

end

app/models/team_has_d.rb
class TeamHasD < ActiveRecord::Base

	belongs_to :dPlay
	belongs_to :team
	has_many :games


	def dTeamAndPlay
		"#{tname.titleize}"
	end
end

app/controllers/team_has_ds_controller.rb
class TeamHasDsController < ApplicationController
  before_action :set_team_has_d, only: [:show, :edit, :update, :destroy]

  # GET /team_has_ds
  # GET /team_has_ds.json
  def index
    @team_has_ds = TeamHasD.all
    @team_has_d = TeamHasD.new
  end

  # GET /team_has_ds/1
  # GET /team_has_ds/1.json
  def show
  end

  # GET /team_has_ds/new
  def new
    @team_has_d = TeamHasD.new
  end

  # GET /team_has_ds/1/edit
  def edit
  end

  # POST /team_has_ds
  # POST /team_has_ds.json
  def create
    @team_has_d = TeamHasD.new(team_has_d_params)

    respond_to do |format|
      if @team_has_d.save
        format.html { redirect_to @team_has_d, notice: 'Team has d was successfully created.' }
        format.json { render action: 'show', status: :created, location: @team_has_d }
      else
        format.html { render action: 'new' }
        format.json { render json: @team_has_d.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /team_has_ds/1
  # PATCH/PUT /team_has_ds/1.json
  def update
    respond_to do |format|
      if @team_has_d.update(team_has_d_params)
        format.html { redirect_to @team_has_d, notice: 'Team has d was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @team_has_d.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_has_ds/1
  # DELETE /team_has_ds/1.json
  def destroy
    @team_has_d.destroy
    respond_to do |format|
      format.html { redirect_to team_has_ds_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team_has_d
      @team_has_d = TeamHasD.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_has_d_params
      params.require(:team_has_d).permit(:team_id, :dPlay_id)
    end
end

app/helpers/team_has_ds_helper.rb
module TeamHasDsHelper
end

app/views/team_has_ds/_form.html.erb
<%= form_for(@team_has_d) do |f| %>
<h1>Add Team D-Play</h1>
	<div class="field">
    	<%= f.label "Team Name" %><br />
		<%= f.collection_select :team_id, Team.all, :id, :tname, :prompt => 'Select A Team' %>
  	</div>
  	<div class="field">
    	<%= f.label "Select Play" %><br />
		<%= f.collection_select :dPlay_id, DPlay.all, :id, :dplayname, :prompt => 'Select A Play' %>
  	</div>
  	<div class="actions">
    	<%= f.submit %>
  	</div>
<% end %>

app/views/team_has_ds/edit.html.erb
<h1>Editing team_has_d</h1>

<%= render 'form' %>

<%= link_to 'Show', @team_has_d %> |
<%= link_to 'Back', team_has_ds_path %>

app/views/team_has_ds/index.html.erb
<h1>Team D-Playbooks</h1>
    <% @team_has_ds.each do |team_has_d| %>
        <%= team_has_d.team_id %>
        <%= team_has_d.dPlay_id %>
        <%= link_to 'Destroy', team_has_d, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
<%= render 'form' %>

app/views/team_has_ds/new.html.erb
<h1>New team_has_d</h1>

<%= render 'form' %>

<%= link_to 'Back', team_has_ds_path %>

app/views/team_has_ds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team:</strong>
  <%= @team_has_d.team_id %>
</p>

<p>
  <strong>Dplay:</strong>
  <%= @team_has_d.dPlay_id %>
</p>

<%= link_to 'Edit', edit_team_has_d_path(@team_has_d) %> |
<%= link_to 'Back', team_has_ds_path %>