config/routes.rb
Audible::Application.routes.draw do
  resources :games

  resources :team_has_os

  resources :team_has_ds

  resources :o_plays

  resources :d_plays

  resources :teams

  root 'home#index'

end

app/models/game.rb
class Game < ActiveRecord::Base

	belongs_to :teamHasO
	belongs_to :teamHasD

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
    @game = Game.new
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:teamHasO_id, :teamHasD_id, :qtr, :clock, :down, :yds_togo, :side, :yd_line, :ball_pos, :pass_dist, :pass_dir, :run_type, :run_loc, :run_dir, :result, :score_diff)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
<h1>Add Game Play</h1>
  	<div class="field">
    	<%= f.label "Select Offense + Play" %><br />
		<%= f.collection_select :teamHasO_id, TeamHasO.all, :id, :oTeamAndPlay, :prompt => 'Select O' %>
  	</div>
  	<div class="field">
    	<%= f.label "Select Defense + Play" %><br />
		<%= f.collection_select :teamHasD_id, TeamHasD.all, :id, :dTeamAndPlay, :prompt => 'Select D' %>
  	</div>
  	<div class="field">
		<%= radio_button_tag(:qtr, 1) %>
		<%= label_tag(:qtr, "1st Quarter") %>
		<%= radio_button_tag(:qtr, 2) %>
		<%= label_tag(:qtr, "2nd Quarter") %>
		<%= radio_button_tag(:qtr, 3) %>
		<%= label_tag(:qtr, "3rd Quarter") %>
		<%= radio_button_tag(:qtr, 4) %>
		<%= label_tag(:qtr, "4th Quarter") %>
  	</div>
  	<div class="field">
    	<%= f.label :clock %><br>
    	<%= f.time_select :clock, :start_hour => 0, :end_hour => 15 %>
 	</div>
  	<div class="field">
		<%= radio_button_tag(:down, 1) %>
		<%= label_tag(:down, "1st Down") %>
		<%= radio_button_tag(:down, 2) %>
		<%= label_tag(:down, "2nd Down") %>
		<%= radio_button_tag(:down, 3) %>
		<%= label_tag(:down, "3rd Down") %>
		<%= radio_button_tag(:down, 4) %>
		<%= label_tag(:down, "4th Down") %>
  	</div>
  	<div class="field">
    	<%= f.label :yds_togo %><br>
    	<%= f.number_field :yds_togo %>
  	</div>
  	<div class="field">
		<%= radio_button_tag(:side, "Out") %>
		<%= label_tag(:side, "Out") %>
		<%= radio_button_tag(:side, "In") %>
		<%= label_tag(:side, "In") %>
  	</div>
  	<div class="field">
    	<%= f.label :yd_line %><br>
    	<%= f.number_field :yd_line %>
  	</div>
  	<div class="field">
		<%= radio_button_tag(:ball_pos, "Left Hash") %>
		<%= label_tag(:ball_pos, "Left Hash") %>
		<%= radio_button_tag(:ball_pos, "Middle") %>
		<%= label_tag(:ball_pos, "Middle") %>
		<%= radio_button_tag(:ball_pos, "Right Hash") %>
		<%= label_tag(:ball_pos, "Right Hash") %>
  	</div>
  	<div class="field">
    	<%= f.label :pass_dist %><br>
		<%= radio_button_tag(:pass_dist, "Short") %>
		<%= label_tag(:pass_dist, "Short") %>
		<%= radio_button_tag(:pass_dist, "Medium") %>
		<%= label_tag(:pass_dist, "Medium") %>
		<%= radio_button_tag(:pass_dist, "Long") %>
		<%= label_tag(:pass_dist, "Long") %>    	
  	</div>
  	<div class="field">
    	<%= f.label :pass_dir %><br>
		<%= radio_button_tag(:pass_dir, "Left") %>
		<%= label_tag(:pass_dir, "Left") %>
		<%= radio_button_tag(:pass_dir, "Middle") %>
		<%= label_tag(:pass_dir, "Middle") %>
		<%= radio_button_tag(:pass_dir, "Right") %>
		<%= label_tag(:pass_dir, "Right") %> 
  	</div>
  	<div class="field">
		<%= radio_button_tag(:run_type, "Handoff") %>
		<%= label_tag(:run_type, "Handoff") %> 
		<%= radio_button_tag(:run_type, "Pitch") %>
		<%= label_tag(:run_type, "Pitch") %>
    	<%= f.label :run_type %><br>
		<%= radio_button_tag(:run_type, "Sweep") %>
		<%= label_tag(:run_type, "Sweep") %>
		<%= radio_button_tag(:run_type, "Draw") %>
		<%= label_tag(:run_type, "Draw") %>
		<%= radio_button_tag(:run_type, "Reverse") %>
		<%= label_tag(:run_type, "Reverse") %> 
 	</div>
  	<div class="field">
    	<%= f.label :run_loc %><br>
		<%= radio_button_tag(:run_loc, "Inside") %>
		<%= label_tag(:run_loc, "Inside") %>
		<%= radio_button_tag(:run_loc, "Tackle") %>
		<%= label_tag(:run_loc, "Tackle") %>
		<%= radio_button_tag(:run_loc, "Outside") %>
		<%= label_tag(:run_loc, "Outside") %> 
  	</div>
  	<div class="field">
    	<%= f.label :run_dir %><br>
		<%= radio_button_tag(:run_dir, "Left") %>
		<%= label_tag(:run_dir, "Left") %>
		<%= radio_button_tag(:run_dir, "Middle") %>
		<%= label_tag(:run_dir, "Middle") %>
		<%= radio_button_tag(:run_dir, "Right") %>
		<%= label_tag(:run_dir, "Right") %> 
  	</div>
  	<div class="field">
    	<%= f.label :result %><br>
    	<%= f.number_field :result %>
  	</div>
  	<div class="field">
    	<%= f.label :score_diff %><br>
    	<%= f.number_field :score_diff %>
  	</div>
  	<div class="actions">
    	<%= f.submit %>
  	</div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Game Rollup</h1>
      Teamhaso
      Teamhasd
      Qtr
      Clock
      Down
      Yds togo
      Side
      Yd line
      Ball pos
      Pass dist
      Pass dir
      Run type
      Run loc
      Run dir
      Result
      Score diff
    <% @games.each do |game| %>
        <%= game.teamHasO_id %>
        <%= game.teamHasD_id %>
        <%= game.qtr %>
        <%= game.clock %>
        <%= game.down %>
        <%= game.yds_togo %>
        <%= game.side %>
        <%= game.yd_line %>
        <%= game.ball_pos %>
        <%= game.pass_dist %>
        <%= game.pass_dir %>
        <%= game.run_type %>
        <%= game.run_loc %>
        <%= game.run_dir %>
        <%= game.result %>
        <%= game.score_diff %>
        <%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
<%= render 'form' %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Teamhaso:</strong>
  <%= @game.teamHasO_id %>
</p>

<p>
  <strong>Teamhasd:</strong>
  <%= @game.teamHasD_id %>
</p>

<p>
  <strong>Qtr:</strong>
  <%= @game.qtr %>
</p>

<p>
  <strong>Clock:</strong>
  <%= @game.clock %>
</p>

<p>
  <strong>Down:</strong>
  <%= @game.down %>
</p>

<p>
  <strong>Yds togo:</strong>
  <%= @game.yds_togo %>
</p>

<p>
  <strong>Side:</strong>
  <%= @game.side %>
</p>

<p>
  <strong>Yd line:</strong>
  <%= @game.yd_line %>
</p>

<p>
  <strong>Ball pos:</strong>
  <%= @game.ball_pos %>
</p>

<p>
  <strong>Pass dist:</strong>
  <%= @game.pass_dist %>
</p>

<p>
  <strong>Pass dir:</strong>
  <%= @game.pass_dir %>
</p>

<p>
  <strong>Run type:</strong>
  <%= @game.run_type %>
</p>

<p>
  <strong>Run loc:</strong>
  <%= @game.run_loc %>
</p>

<p>
  <strong>Run dir:</strong>
  <%= @game.run_dir %>
</p>

<p>
  <strong>Result:</strong>
  <%= @game.result %>
</p>

<p>
  <strong>Score diff:</strong>
  <%= @game.score_diff %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>