config/routes.rb
Audible::Application.routes.draw do
  resources :games

  resources :team_has_os

  resources :team_has_ds

  resources :o_plays

  resources :d_plays

  resources :teams

  root 'home#index'

end

app/models/o_play.rb
class OPlay < ActiveRecord::Base

	has_many :teamHasOs

	def oplayname
		"#{name.titleize}"
	end
end

app/controllers/o_plays_controller.rb
class OPlaysController < ApplicationController
  before_action :set_o_play, only: [:show, :edit, :update, :destroy]

  # GET /o_plays
  # GET /o_plays.json
  def index
    @o_plays = OPlay.all
    @o_play = OPlay.new
  	@o_formations = OPlay.all
  end

  # GET /o_plays/1
  # GET /o_plays/1.json
  def show
  end

  # GET /o_plays/new
  def new
    @o_play = OPlay.new
  end

  # GET /o_plays/1/edit
  def edit
  end

  # POST /o_plays
  # POST /o_plays.json
  def create
    @o_play = OPlay.new(o_play_params)

    respond_to do |format|
      if @o_play.save
        format.html { redirect_to o_plays_url, notice: 'O play was successfully created.' }
        format.json { render action: 'show', status: :created, location: @o_play }
      else
        format.html { render action: 'new' }
        format.json { render json: @o_play.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /o_plays/1
  # PATCH/PUT /o_plays/1.json
  def update
    respond_to do |format|
      if @o_play.update(o_play_params)
        format.html { redirect_to @o_play, notice: 'O play was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @o_play.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /o_plays/1
  # DELETE /o_plays/1.json
  def destroy
    @o_play.destroy
    respond_to do |format|
      format.html { redirect_to o_plays_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_o_play
      @o_play = OPlay.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def o_play_params
      params.require(:o_play).permit(:name, :picture, :formation, :play_type)
    end
end

app/helpers/o_plays_helper.rb
module OPlaysHelper
end

app/views/o_plays/_form.html.erb
<%= form_for(@o_play) do |f| %>
<div id="o-form">
<h1>Add Offensive Play</h1>
	<div class="field">
    	<%= f.label :name %><br>
    	<%= f.text_field :name %>
    </div>
  	<div class="field">
    	<%= f.label :picture %><br>
    	<%= f.text_field :picture %>
  	</div>
  	<div class="field">
    	<%= f.label :formation %><br>
    	<%= f.text_field :formation %>
  	</div>
  	<div class="field">
    	<%= f.label :play_type %><br>
    	<%= f.text_field :play_type %>
  	</div>
  	<div class="actions">
    	<%= f.submit %>
  	</div>
</div>
<% end %>

app/views/o_plays/edit.html.erb
<h1>Editing o_play</h1>

<%= render 'form' %>

app/views/o_plays/index.html.erb
<div id="o-backdrop">
	<div id="o-list">
		<% @o_formations.each do |o_formation| %>
			<h2><%= o_formation.formation %></h2>
			<% @o_plays.each do |o_play| %>
			<% if o_formation.formation == o_play.formation %>
				<div id="indy-o">
					<p class="playname"><%= o_play.name %></p>
					<p class="imageplay"><%= image_tag o_play.picture %></p>
					<p class="playtype"><%= o_play.play_type %></p>
				</div>
			<% else %>
			<% end %>
			<% end %>
		<% end %>
	</div>
	<%= render 'form' %>
</div>

app/views/o_plays/new.html.erb
<h1>New o_play</h1>

<%= render 'form' %>

<%= link_to 'Back', o_plays_path %>

app/views/o_plays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @o_play.name %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @o_play.picture %>
</p>

<p>
  <strong>Formation:</strong>
  <%= @o_play.formation %>
</p>

<p>
  <strong>Play type:</strong>
  <%= @o_play.play_type %>
</p>

<%= link_to 'Edit', edit_o_play_path(@o_play) %> |
<%= link_to 'Back', o_plays_path %>